import type { Character } from "./App";

export const CHARACTERS: Character[] = [
  { id: "char_adam", name: "Adam", expansionId: "S1" },
  { id: "char_ahmed_yasin", name: "Ahmed Yasin", expansionId: "S1" },
  { id: "char_borden", name: "Borden", expansionId: "S1" },
  { id: "char_elizabeth_ives", name: "Elizabeth Ives", expansionId: "S1" },
  { id: "char_fatima_safar", name: "Fatima Safar", expansionId: "S1" },
  { id: "char_sergeant_ian_welles", name: "Sergeant Ian Welles", expansionId: "S1", },
  { id: "char_john_morgan", name: "John Morgan", expansionId: "S1" },
  { id: "char_rasputin", name: "Rasputin", expansionId: "S1" },
  { id: "char_sister_beth", name: "Sister Beth", expansionId: "S1" },
  { id: "char_the_kid", name: "The Kid", expansionId: "S1" },
  { id: "char_adilah_vidal", name: "Adilah Vidal", expansionId: "S2" },
  { id: "char_alex_parker", name: "Alex Parker", expansionId: "S2" },
  { id: "char_ariele_venturi", name: "Arielle Venturi", expansionId: "S2" },
  { id: "char_hailia_hovath", name: "Hailia Hovath", expansionId: "S2" },
  { id: "char_father_luke", name: "Father Luke", expansionId: "S2" },
  { id: "char_margarethe_richter", name: "Margarethe Richter", expansionId: "S2", },
  { id: "char_sergeant_mario_braghieri", name: "Sergeant Mario Braghieri", expansionId: "S2", },
  { id: "char_mary_diaz", name: "Mary Diaz", expansionId: "S2" },
  { id: "char_sam_wood", name: "Sam", expansionId: "S2" },
  { id: "char_tony_boyle", name: "Tony Boyle", expansionId: "S2" },
  { id: "char_agatha_may", name: "Agatha May", expansionId: "S3" },
  { id: "char_huikong", name: "Huikong", expansionId: "S3" },
  { id: "char_julien_dulik", name: "Julien Dulik", expansionId: "S3" },
  { id: "char_leon_barnes", name: "Leon Barnes", expansionId: "S3" },
  { id: "char_mike_kozlov", name: "Mike Kozlov", expansionId: "S3" },
  { id: "char_jakub_peters", name: "Jakub Peters", expansionId: "S3" },
  { id: "char_ruth_weber", name: "Ruth Weber", expansionId: "S3" },
  { id: "char_sally_withers", name: "Sally Withers", expansionId: "S3" },
  { id: "char_sandra_atkinson", name: "Sandra Atkinson", expansionId: "S3" },
  { id: "char_stella_fontaine", name: "Stella Fontaine", expansionId: "S3" },
  { id: "char_anika_biko", name: "Anika Biko", expansionId: "S4" },
  { id: "char_bruno_vitale", name: "Bruno Vitale", expansionId: "S4" },
  { id: "char_gary_west", name: "Gary West", expansionId: "S4" },
  { id: "char_john_fernsby", name: "John Fernsby", expansionId: "S4" },
  { id: "char_rosario_guerrera", name: "Rosario Guerrera", expansionId: "S4" },
  { id: "char_anna_and_belle", name: "Anna and Belle", expansionId: "S4" },
  { id: "char_denise_rousseau", name: "Denise Rousseau", expansionId: "S5" },
  { id: "char_godfrey_bourne", name: "Godfrey Bourne", expansionId: "S5" },
  { id: "char_harry_larson", name: "Harry Larson", expansionId: "S5" },
  { id: "char_jaime_gusmão", name: "Jaime Gusmão", expansionId: "S5" },
  { id: "char_julius_johns", name: "Julius Johns", expansionId: "S5" },
  { id: "char_katya_morozova", name: "Katya Morozova", expansionId: "S5" },
  { id: "char_nathan_wayne", name: "Nathan Wayne", expansionId: "S5" },
  { id: "char_simone_sinclair", name: "Simone Sinclair", expansionId: "S5" },
  { id: "char_yuqi_wan", name: "Yuqi Wan", expansionId: "S5" },
  { id: "char_aisha_adams", name: "Aisha Adams", expansionId: "S6" },
  { id: "char_artemisia_greco", name: "Artemisia Greco", expansionId: "S6" },
  { id: "char_freddy", name: "Freddy", expansionId: "S6" },
  { id: "char_lilian_gray", name: "Lilian Gray", expansionId: "S6" },
  { id: "char_matteo_torre", name: "Matteo Torre", expansionId: "S6" },
  { id: "char_ralph_hardee", name: "Ralph Hardee", expansionId: "S6" },
  { id: "char_al_capone", name: "Al Capone", expansionId: "Unspeakable Box" },
  { id: "char_albert_einstein", name: "Albert Einstein", expansionId: "Unspeakable Box" },
  { id: "char_ernest_hemingway", name: "Ernest Hemingway", expansionId: "Unspeakable Box", }, 
  { id: "char_fleur_dubois", name: "Fleur Dubois", expansionId: "Unspeakable Box", }, 
  { id: "char_julia_hollister", name: "Julia Hollister", expansionId: "Unspeakable Box", }, 
  { id: "char_josephine_leclerc", name: "Josephine Leclerc", expansionId: "Unspeakable Box", }, 
  { id: "char_marcelo_gonk_conçalves", name: "Marcelo 'Gonk' Conçalves", expansionId: "Unspeakable Box", }, 
  { id: "char_maki_smith", name: "Maki Smith", expansionId: "Unspeakable Box" }, 
  { id: "char_margie_westmoreland", name: "Margie Westmoreland", expansionId: "Unspeakable Box", }, 
  { id: "char_maxim_grey", name: "Maxim Grey", expansionId: "Unspeakable Box" }, 
  { id: "char_meryl_starling", name: "Meryl Starling", expansionId: "Unspeakable Box", }, 
  { id: "char_olivia_duchamp", name: "Olivia Duchamp", expansionId: "Unspeakable Box", }, 
  { id: "char_professor_vincent_haas", name: "Professor Vincent Haas", expansionId: "Unspeakable Box", }, 
  { id: "char_pops_duperon", name: "Pops Duperon", expansionId: "Unspeakable Box", }, 
  { id: "char_richard_irons", name: "Richard Irons", expansionId: "Unspeakable Box", }, 
  { id: "char_roxie_mitchell_williams", name: "Roxie Mitchell Williams", expansionId: "Unspeakable Box", }, 
  { id: "char_tina_macshane", name: "Tina MacShane", expansionId: "Unspeakable Box", }, 
  { id: "char_walter_bagget", name: "Walter Bagget", expansionId: "Unspeakable Box", }, 
  { id: "char_agnes_fortin", name: "Agnes Fortin", expansionId: "Unknowable Box", }, 
  { id: "char_amelie_crowe", name: "Amelie Crowe", expansionId: "Unknowable Box", }, 
  { id: "char_amir_sesay", name: "Amir Sesay", expansionId: "Unknowable Box" }, 
  { id: "char_anita_khalil", name: "Anita Khalil", expansionId: "Unknowable Box", }, 
  { id: "char_antonio_senatore", name: "Antonio Senatore", expansionId: "Unknowable Box", }, 
  { id: "char_archie_fort", name: "Archie Fort", expansionId: "Unknowable Box", }, 
  { id: "char_buck_hall", name: "Buck Hall", expansionId: "Unknowable Box" }, 
  { id: "char_charles_hollar", name: "Charles Hollar", expansionId: "Unknowable Box", }, 
  { id: "char_craig_adamson", name: "Craig Adamson", expansionId: "Unknowable Box", },
  { id: "char_don_hayworth", name: "Don Hayworth", expansionId: "Unknowable Box", }, 
  { id: "char_dorothy_parker", name: "Dorothy Parker", expansionId: "Unknowable Box", }, 
  { id: "char_eve_blanchett", name: "Eve Blanchett", expansionId: "Unknowable Box", }, 
  { id: "char_george_rodriguez", name: "George Rodriguez", expansionId: "Unknowable Box", }, 
  { id: "char_harry_houdini", name: "Harry Houdini", expansionId: "Unknowable Box", }, 
  { id: "char_ikeda_saito", name: "Ikeda Saito", expansionId: "Unknowable Box", }, 
  { id: "char_isadora_rocha", name: "Isadora Rocha", expansionId: "Unknowable Box", }, 
  { id: "char_james_dalton", name: "James Dalton", expansionId: "Unknowable Box", }, 
  { id: "char_jim_cannon", name: "Jim Cannon", expansionId: "Unknowable Box" }, 
  { id: "char_karen_mendel", name: "Karen Mendel", expansionId: "Unknowable Box", }, 
  { id: "char_martin_horner", name: "Martin Horner", expansionId: "Unknowable Box", }, 
  { id: "char_michelle_hart", name: "Michelle Hart", expansionId: "Unknowable Box", }, 
  { id: "char_robert_gray", name: "Robert Gray", expansionId: "Unknowable Box", }, 
  { id: "char_ryan_martell", name: "Ryan Martell", expansionId: "Unknowable Box", }, 
  { id: "char_salvador_dali", name: "Salvador Dali", expansionId: "Unknowable Box", }, 
  { id: "char_steve_wainwright", name: "Steve Wainwright", expansionId: "Unknowable Box", }, 
  { id: "char_taylor_renner", name: "Taylor Renner", expansionId: "Unknowable Box", }, 
  { id: "char_tom_gilman", name: "Tom Gilman", expansionId: "Unknowable Box" }, 
  { id: "char_vanessa_ortiz", name: "Vanessa Ortiz", expansionId: "Unknowable Box", }, 
  { id: "char_abdul_alhazred", name: "Abdul Alhazred", expansionId: "Unimaginable Box", }, 
  { id: "char_azelia_johnson", name: "Azelia Johnson", expansionId: "Unimaginable Box", }, 
  { id: "char_boris_karloff", name: "Boris Karloff", expansionId: "Unimaginable Box", }, 
  { id: "char_cab_colloway", name: "Cab Colloway", expansionId: "Unimaginable Box", }, 
  { id: "char_dr_herbert_west", name: "Dr. Herbert West", expansionId: "Unimaginable Box", }, 
  { id: "char_faust", name: "Faust", expansionId: "Unimaginable Box" }, 
  { id: "char_frida_kahlo", name: "Frida Kahlo", expansionId: "Unimaginable Box", }, 
  { id: "char_hu_die", name: "Hu Die", expansionId: "Unimaginable Box" }, 
  { id: "char_joan_crawford", name: "Joan Crawford", expansionId: "Unimaginable Box", }, 
  { id: "char_kenji_takahashi", name: "Kenji Takahashi", expansionId: "Unimaginable Box", }, 
  { id: "char_larry_carmine", name: "Larry Carmine", expansionId: "Unimaginable Box", }, 
  { id: "char_ludwig_bauer", name: "Ludwig Bauer", expansionId: "Unimaginable Box", }, 
  { id: "char_marlene_dietrich", name: "Marlene Dietrich", expansionId: "Unimaginable Box", }, 
  { id: "char_max_schreck", name: "Max Schreck", expansionId: "Unimaginable Box", }, 
  { id: "char_nate_mccoy", name: "Nate McCoy", expansionId: "Unimaginable Box", }, 
  { id: "char_nikola_tesla", name: "Nikola Tesla ", expansionId: "Unimaginable Box", }, 
  { id: "char_remy_dakanotic", name: "Remy Dakanotic", expansionId: "Unimaginable Box", }, 
  { id: "char_rita_marunchak", name: "Rita Marunchak", expansionId: "Unimaginable Box", }, 
  { id: "char_santos_dumont", name: "Santos Dumont", expansionId: "Unimaginable Box", }, 
  { id: "char_tarsila_do_ameral", name: "Tarsila do Amaral", expansionId: "Unimaginable Box", }, 
  { id: "char_virginia_woolf ", name: "Virginia Woolf ", expansionId: "Unimaginable Box", }, 
  { id: "char_zelda_fitzgerald", name: "Zelda Fitzgerald", expansionId: "Unimaginable Box", }, 
  { id: "char_allan_jenkins", name: "Allan Jenkins", expansionId: "Comic Book Vol. 1", }, 
  { id: "char_annabelle_laveau", name: "Annabelle Laveau", expansionId: "Comic Book Vol. 1", }, 
  { id: "char_jack_munoz", name: "Jack Muñoz", expansionId: "Comic Book Vol. 1", },
  { id: "char_lysa", name: "Lysa", expansionId: "Comic Book Vol. 1" },
  { id: "char_rocco", name: "Rocco", expansionId: "Comic Book Vol. 1" },
  { id: "char_tamara", name: "Tamara", expansionId: "Comic Book Vol. 1" },
  { id: "char_ethan", name: "Ethan", expansionId: "Comic Book Vol. 2" },
  { id: "char_ezra", name: "Ezra", expansionId: "Comic Book Vol. 2" },
  { id: "char_olmstead", name: "Olmstead", expansionId: "Comic Book Vol. 2" },
  { id: "char_veronique", name: "Veronique", expansionId: "Comic Book Vol. 2" },
  { id: "char_virginia_lyman", name: "Virginia Lyman", expansionId: "Comic Book Vol. 2", }, 
  { id: "char_asylum_eddie", name: "Asylum Eddie", expansionId: "Iron Maiden" }, 
  { id: "char_scarlett", name: "Scarlett Hayes", expansionId: "Scarlett", }, 
  { id: "char_agent_monday", name: "Agent Monday", expansionId: "Dark Providence Preorder", }, 
  { id: "char_agent_tuesday", name: "Agent Tuesday", expansionId: "Dark Providence Preorder", }, 
  { id: "char_agent_wednesday", name: "Agent Wednesday", expansionId: "Dark Providence Preorder", }, 
  { id: "char_agent_thursday", name: "Agent Thursday", expansionId: "Dark Providence Preorder", }, 
  { id: "char_agent_friday", name: "Agent Friday", expansionId: "Dark Providence Preorder", }, 
  { id: "char_robinson_crusoe", name: "Robinson Crusoe", expansionId: "Portal Games 25th Anniversary Promo", },
];
