import type { Character } from "./App";

export const CHARACTERS: Character[] = [
  { id: "char_lord_adam_benchley", name: "Lord Adam Benchley", shortName: "Adam", expansionId: "S1" },
  { id: "char_ahmed_yasin", name: "Ahmed Yasin", shortName: "Ahmed", expansionId: "S1" },
  { id: "char_borden", name: "Borden", expansionId: "S1" },
  { id: "char_elizabeth_ives", name: "Elizabeth Ives", shortName: "Elizabeth", expansionId: "S1" },
  { id: "char_fatima_safar", name: "Fatima Safar", shortName: "Fatima", expansionId: "S1" },
  { id: "char_sergeant_ian_welles", name: "Sergeant Ian Welles", shortName: "Ian", expansionId: "S1", },
  { id: "char_john_morgan", name: "John Morgan", shortName: "John", expansionId: "S1" },
  { id: "char_rasputin", name: "Rasputin", expansionId: "S1" },
  { id: "char_sister_beth", name: "Sister Beth", shortName: "Beth", expansionId: "S1" },
  { id: "char_the_kid", name: "The Kid",  expansionId: "S1" },
  { id: "char_adilah_vidal", name: "Adilah Vidal", shortName: "Adilah", expansionId: "S2" },
  { id: "char_alex_parker", name: "Alex Parker", shortName: "Alex", expansionId: "S2" },
  { id: "char_ariele_venturi", name: "Ariele Venturi", shortName: "Ariele", expansionId: "S2" },
  { id: "char_hailia_hovath", name: "Hailia Hovath", shortName: "Hailia", expansionId: "S2" },
  { id: "char_father_luke", name: "Father Luke", shortName: "Luke", expansionId: "S2" },
  { id: "char_margarethe_richter", name: "Margarethe Richter", shortName: "Margarethe", expansionId: "S2", },
  { id: "char_sergeant_mario_braghieri", name: "Sergeant Mario Braghieri", shortName: "Mario", expansionId: "S2", },
  { id: "char_mary_diaz", name: "Mary Diaz", shortName: "Mary", expansionId: "S2" },
  { id: "char_sam_wood", name: "Sam Wood", shortName: "Sam", expansionId: "S2" },
  { id: "char_machinists_mate_tony_boyle", name: "Machinist's Mate Tony Boyle", shortName: "Tony", expansionId: "S2" },
  { id: "char_agatha_may", name: "Agatha May", shortName: "Agatha", expansionId: "S3" },
  { id: "char_huikong", name: "Huikong", shortName: "Huikong", expansionId: "S3" },
  { id: "char_julien_dulik", name: "Julien Dulik", shortName: "Julien", expansionId: "S3" },
  { id: "char_leon_barnes", name: "Leon Barnes", shortName: "Leon", expansionId: "S3" },
  { id: "char_mike_kozlov", name: "Mike Kozlov", shortName: "Mike", expansionId: "S3" },
  { id: "char_jakub_peters", name: "Jakub Peters", shortName: "Jakub", expansionId: "S3" },
  { id: "char_ruth_weber", name: "Ruth Weber", shortName: "Ruth", expansionId: "S3" },
  { id: "char_sally_withers", name: "Sally Withers", shortName:"Sally" , expansionId:"S3"},
  { id: "char_sandra_atkinson", name: "Sandra Atkinson", shortName: "Sandra", expansionId: "S3" },
  { id: "char_stella_fontaine", name: "Stella Fontaine", shortName: "Stella", expansionId: "S3" },
  { id: "char_anika_biko", name: "Anika Biko", shortName: "Anika", expansionId: "S4" },
  { id: "char_bruno_vitale", name: "Bruno Vitale", shortName: "Bruno", expansionId: "S4" },
  { id: "char_gary_west", name: "Gary West", shortName: "Gary", expansionId: "S4" },
  { id: "char_john_fernsby", name: "John Fernsby", shortName:"John" , expansionId:"S4"},
  { id: "char_rosario_guerrera", name: "Rosario Guerrera", shortName: "Rosario", expansionId: "S4" },
  { id: "char_anna_and_belle", name: "Anna and Belle", shortName:"Anna & Belle" , expansionId:"S4"},
  { id: "char_denise_rousseau", name: "Denise Rousseau", shortName: "Denise", expansionId: "S5" },
  { id: "char_godfrey_bourne", name: "Godfrey Bourne", shortName: "Godfrey", expansionId: "S5" },
  { id: "char_harry_larson", name: "Harry Larson", shortName: "Harry", expansionId: "S5" },
  { id: "char_jaime_gusmão", name: "Jaime Gusmão", shortName:"Jaime" , expansionId:"S5"},
  { id: "char_julius_johns", name: "Julius Johns", shortName:"Julius" , expansionId:"S5"},
  { id: "char_katya_morozova", name: "Katya Morozova", shortName:"Katya" , expansionId:"S5"},
  { id: "char_nathan_wayne", name: "Nathan Wayne", shortName:"Nathan" , expansionId:"S5"},
  { id: "char_simone_sinclair", name: "Simone Sinclair", shortName:"Simone" , expansionId:"S5"},
  { id: "char_yuqi_wan", name: "Yuqi Wan", shortName:"Yuqi" , expansionId:"S5"},
  { id: "char_aisha_adams", name: "Aisha Adams", shortName:"Aisha" , expansionId:"S6"},
  { id: "char_artemisia_greco", name: "Artemisia Greco", shortName:"Artemisia" , expansionId:"S6"},
  { id: "char_freddy", name: "Freddy", shortName:"Freddy" , expansionId:"S6"},
  { id: "char_lilian_gray", name: "Lilian Gray", shortName:"Lilian" , expansionId:"S6"},
  { id: "char_matteo_torre", name: "Matteo Torre", shortName:"Matteo" , expansionId:"S6"},
  { id: "char_ralph_hardee", name: "Ralph Hardee", shortName:"Ralph" , expansionId:"S6"},
  { id: "char_al_capone", name: "Al Capone", shortName:"Al" , expansionId:"Unspeakable Box"},
  { id: "char_albert_einstein", name: "Albert Einstein", shortName:"Albert" , expansionId:"Unspeakable Box"},
  { id: "char_ernest_hemingway", name: "Ernest Hemingway", shortName:"Ernest" , expansionId:"Unspeakable Box"}, 
  { id: "char_fleur_dubois", name: "Fleur Dubois", shortName:"Fleur" , expansionId:"Unspeakable Box"}, 
  { id: "char_julia_hollister", name: "Julia Hollister", shortName:"Julia" , expansionId:"Unspeakable Box"}, 
  { id: "char_josephine_leclerc", name: "Josephine Leclerc", shortName:"Josephine" , expansionId:"Unspeakable Box", }, 
  { id: "char_marcelo_gonk_conçalves", name: "Marcelo 'Gonk' Conçalves", shortName:"Gonk" , expansionId:"Unspeakable Box", }, 
  { id: "char_maki_smith", name: "Maki Smith", shortName:"Maki" , expansionId:"Unspeakable Box" }, 
  { id: "char_margie_westmoreland", name: "Margie Westmoreland", shortName:"Margie" , expansionId:"Unspeakable Box", }, 
  { id: "char_maxim_grey", name: "Maxim Grey", shortName:"Maxim" , expansionId:"Unspeakable Box" }, 
  { id: "char_meryl_starling", name: "Meryl Starling", shortName:"Meryl" , expansionId: "Unspeakable Box", }, 
  { id: "char_olivia_duchamp", name: "Olivia Duchamp", shortName:"Olivia" , expansionId: "Unspeakable Box", }, 
  { id: "char_professor_vincent_haas", name: "Professor Vincent Haas", shortName:"Vincent" , expansionId: "Unspeakable Box", }, 
  { id: "char_pops_duperon", name: "Pops Duperon", shortName:"Pops" , expansionId: "Unspeakable Box", }, 
  { id: "char_richard_irons", name: "Richard Irons", shortName:"Richard" , expansionId: "Unspeakable Box", }, 
  { id: "char_roxie_mitchell_williams", name: "Roxie Mitchell Williams", shortName:"Roxie" , expansionId: "Unspeakable Box", }, 
  { id: "char_tina_macshane", name: "Tina MacShane", shortName:"Tina" , expansionId: "Unspeakable Box", }, 
  { id: "char_walter_bagget", name: "Walter Bagget", shortName:"Walter" , expansionId: "Unspeakable Box", }, 
  { id: "char_agnes_fortin", name: "Agnes Fortin", shortName:"Agnes" , expansionId: "Unknowable Box", }, 
  { id: "char_amelie_crowe", name: "Amelie Crowe", shortName:"Amelie" , expansionId: "Unknowable Box", }, 
  { id: "char_amir_sesay", name: "Amir Sesay", shortName:"Amir" , expansionId: "Unknowable Box" }, 
  { id: "char_anita_khalil", name: "Anita Khalil", shortName:"Anita" , expansionId: "Unknowable Box", }, 
  { id: "char_antonio_senatore", name: "Antonio Senatore", shortName:"Antonio" , expansionId: "Unknowable Box", }, 
  { id: "char_archie_fort", name: "Archie Fort", shortName:"Archie" , expansionId: "Unknowable Box", }, 
  { id: "char_buck_hall", name: "Buck Hall", shortName:"Buck" , expansionId: "Unknowable Box" }, 
  { id: "char_charles_hollar", name: "Charles Hollar", shortName:"Charles" , expansionId: "Unknowable Box", }, 
  { id: "char_craig_adamson", name: "Craig Adamson", shortName:"Craig" , expansionId: "Unknowable Box", },
  { id: "char_don_hayworth", name: "Don Hayworth", shortName:"Don" , expansionId: "Unknowable Box", }, 
  { id: "char_dorothy_parker", name: "Dorothy Parker", shortName:"Dorothy" , expansionId: "Unknowable Box", }, 
  { id: "char_eve_blanchett", name: "Eve Blanchett", shortName:"Eve" , expansionId: "Unknowable Box", }, 
  { id: "char_george_rodriguez", name: "George Rodriguez", shortName:"George" , expansionId: "Unknowable Box", }, 
  { id: "char_harry_houdini", name: "Harry Houdini", shortName:"Harry" , expansionId: "Unknowable Box", }, 
  { id: "char_ikeda_saito", name: "Ikeda Saito", shortName:"Ikeda" , expansionId: "Unknowable Box", }, 
  { id: "char_isadora_rocha", name: "Isadora Rocha", shortName:"Isadora" , expansionId: "Unknowable Box", }, 
  { id: "char_james_dalton", name: "James Dalton", shortName:"James" , expansionId: "Unknowable Box", }, 
  { id: "char_jim_cannon", name: "Jim Cannon", shortName:"Jim" , expansionId: "Unknowable Box" }, 
  { id: "char_karen_mendel", name: "Karen Mendel", shortName:"Karen" , expansionId: "Unknowable Box", }, 
  { id: "char_martin_horner", name: "Martin Horner", shortName:"Martin" , expansionId: "Unknowable Box", }, 
  { id: "char_michelle_hart", name: "Michelle Hart", shortName:"Michelle" , expansionId: "Unknowable Box", }, 
  { id: "char_robert_gray", name: "Robert Gray", shortName:"Robert" , expansionId: "Unknowable Box", }, 
  { id: "char_ryan_martell", name: "Ryan Martell", shortName:"Ryan" , expansionId: "Unknowable Box", }, 
  { id: "char_salvador_dali", name: "Salvador Dali", shortName:"Salvador" , expansionId: "Unknowable Box", }, 
  { id: "char_steve_wainwright", name: "Steve Wainwright", shortName:"Steve" , expansionId: "Unknowable Box", }, 
  { id: "char_taylor_renner", name: "Taylor Renner", shortName:"Taylor" , expansionId: "Unknowable Box", }, 
  { id: "char_tom_gilman", name: "Tom Gilman", shortName:"Tom" , expansionId: "Unknowable Box" }, 
  { id: "char_vanessa_ortiz", name: "Vanessa Ortiz", shortName:"Vanessa" , expansionId: "Unknowable Box", }, 
  { id: "char_abdul_alhazred", name: "Abdul Alhazred", shortName:"Abdul" , expansionId: "Unimaginable Box", }, 
  { id: "char_azelia_johnson", name: "Azelia Johnson", shortName:"Azelia" , expansionId: "Unimaginable Box", }, 
  { id: "char_boris_karloff", name: "Boris Karloff", shortName:"Boris" , expansionId: "Unimaginable Box", }, 
  { id: "char_cab_colloway", name: "Cab Colloway", shortName:"Cab" , expansionId: "Unimaginable Box", }, 
  { id: "char_dr_herbert_west", name: "Dr. Herbert West", shortName:"Herbert" , expansionId: "Unimaginable Box", }, 
  { id: "char_faust", name: "Faust", shortName:"Faust" , expansionId: "Unimaginable Box" }, 
  { id: "char_frida_kahlo", name: "Frida Kahlo", shortName:"Frida" , expansionId: "Unimaginable Box", }, 
  { id: "char_hu_die", name: "Hu Die", shortName:"Hu Die" , expansionId: "Unimaginable Box" }, 
  { id: "char_joan_crawford", name: "Joan Crawford", shortName:"Joan" , expansionId: "Unimaginable Box", }, 
  { id: "char_kenji_takahashi", name: "Kenji Takahashi", shortName:"Kenji" , expansionId: "Unimaginable Box", }, 
  { id: "char_larry_carmine", name: "Larry Carmine", shortName:"Larry" , expansionId: "Unimaginable Box", }, 
  { id: "char_ludwig_bauer", name: "Ludwig Bauer", shortName:"Ludwig" , expansionId: "Unimaginable Box", }, 
  { id: "char_marlene_dietrich", name: "Marlene Dietrich", shortName:"Marlene" , expansionId: "Unimaginable Box", }, 
  { id: "char_max_schreck", name: "Max Schreck", shortName:"Max" , expansionId: "Unimaginable Box", }, 
  { id: "char_nate_mccoy", name: "Nate McCoy", shortName:"Nate" , expansionId: "Unimaginable Box", }, 
  { id: "char_nikola_tesla", name: "Nikola Tesla ", shortName:"Nikola" , expansionId: "Unimaginable Box", }, 
  { id: "char_remy_dakanotic", name: "Remy Dakanotic", shortName:"Remy" , expansionId: "Unimaginable Box", }, 
  { id: "char_rita_marunchak", name: "Rita Marunchak", shortName:"Rita" , expansionId: "Unimaginable Box", }, 
  { id: "char_santos_dumont", name: "Santos Dumont", shortName:"Santos" , expansionId: "Unimaginable Box", }, 
  { id: "char_tarsila_do_ameral", name: "Tarsila do Amaral", shortName:"Tarsila" , expansionId: "Unimaginable Box", }, 
  { id: "char_virginia_woolf ", name: "Virginia Woolf ", shortName:"Virginia" , expansionId: "Unimaginable Box", }, 
  { id: "char_zelda_fitzgerald", name: "Zelda Fitzgerald", shortName:"Zelda" , expansionId: "Unimaginable Box", }, 
  { id: "char_allan_jenkins", name: "Allan Jenkins", shortName:"Allan" , expansionId: "Comic Book Vol. 1", }, 
  { id: "char_annabelle_laveau", name: "Annabelle Laveau", shortName:"Annabelle" , expansionId: "Comic Book Vol. 1", }, 
  { id: "char_jack_munoz", name: "Jack Muñoz", shortName:"Jack" , expansionId: "Comic Book Vol. 1", },
  { id: "char_lysa", name: "Lysa", shortName:"Lysa" , expansionId: "Comic Book Vol. 1" },
  { id: "char_rocco", name: "Rocco", shortName:"Rocco" , expansionId: "Comic Book Vol. 1" },
  { id: "char_tamara", name: "Tamara", shortName:"Tamara" , expansionId: "Comic Book Vol. 1" },
  { id: "char_ethan", name: "Ethan", shortName:"Ethan" , expansionId: "Comic Book Vol. 2" },
  { id: "char_ezra", name: "Ezra", shortName:"Ezra" , expansionId: "Comic Book Vol. 2" },
  { id: "char_olmstead", name: "Olmstead", shortName:"Olmstead" , expansionId: "Comic Book Vol. 2" },
  { id: "char_veronique", name: "Veronique", shortName:"Veronique" , expansionId: "Comic Book Vol. 2" },
  { id: "char_virginia_lyman", name: "Virginia Lyman", shortName:"Virginia Lyman" , expansionId: "Comic Book Vol. 2", }, 
  { id: "char_asylum_eddie", name: "Asylum Eddie", shortName:"Asylum Eddie" , expansionId: "Iron Maiden" }, 
  { id: "char_scarlett", name: "Scarlett Hayes", shortName:"Scarlett" , expansionId: "Scarlett", }, 
  { id: "char_agent_monday", name: "Agent Monday", shortName:"Agent Monday" , expansionId: "Dark Providence Preorder", }, 
  { id: "char_agent_tuesday", name: "Agent Tuesday", shortName:"Agent Tuesday" , expansionId: "Dark Providence Preorder", }, 
  { id: "char_agent_wednesday", name: "Agent Wednesday", shortName:"Agent Wednesday" , expansionId: "Dark Providence Preorder", }, 
  { id: "char_agent_thursday", name: "Agent Thursday", shortName:"Agent Thursday" , expansionId: "Dark Providence Preorder", }, 
  { id: "char_agent_friday", name: "Agent Friday", shortName:"Agent Friday" , expansionId: "Dark Providence Preorder", }, 
  { id: "char_robinson_crusoe", name: "Robinson Crusoe", shortName:"Robinson Crusoe" , expansionId: "Portal Games 25th Anniversary Promo", },
];
