import type { Scenario } from "./App";

export const SCENARIOS: Scenario[] = [
  { id: "S1E1", name: "Blasphemous alchemy", expansionId: "S1", description: "What's worse then cultist? Cultist who've set the place on fire. Another night and another damn ritual to summon an Elder God. We blow up their labs and we can cause a lot of trouble to whatever it is they are summoning." },
  { id: "S1E2", name: "Tomes of madness", expansionId: "S1", description: "", },
  { id: "S1E3", name: "Danse Macabre", expansionId: "S1", description: "", },
  { id: "S1E4", name: "Eldritch Idols", expansionId: "S1", description: "" },
  { id: "S1E5", name: "Accursed Tide", expansionId: "S1", description: "" },
  { id: "S1E6", name: "Unspeakable Hour", expansionId: "S1", description: "" },
  { id: "S2E1", name: "Strange Bedfellows", expansionId: "S2", description: "", },
  { id: "S2E2", name: "Nameless Woods", expansionId: "S2", description: "" },
  { id: "S2E3", name: "Sanctificetur Nomen", expansionId: "S2", description: "", },
  { id: "S2E4", name: "Creeping Time", expansionId: "S2", description: "" },
  { id: "S2E5", name: "Monster in Sin City", expansionId: "S2", description: "", },
  { id: "S2E6", name: "Endgame", expansionId: "S2", description: "" },
  { id: "S3E1", name: "Isle of the Damned", expansionId: "S3", description: "" },
  { id: "S3E2", name: "Top of the Mourning", expansionId: "S3", description: "" },
  { id: "S3E3", name: "Deliver us from Evil", expansionId: "S3", description: "" },
  { id: "S3E4", name: "By Request of the Queen", expansionId: "S3", description: "" },
  { id: "S3E5", name: "Festival of Death", expansionId: "S3", description: "" },
  { id: "S3E6", name: "Die Schöne und das Biest", expansionId: "S3", description: "" },
  { id: "S4E1", name: "Horror in the Sky", expansionId: "S4", description: "" },
  { id: "S4E2", name: "The Haunted Garden", expansionId: "S4", description: "", },
  { id: "S4E3", name: "Fields of Hell", expansionId: "S4", description: "" },
  { id: "S4E4", name: "Death on the Nile", expansionId: "S4", description: "" },
  { id: "S4E5", name: "Pyramid of Fear", expansionId: "S4", description: "" },
  { id: "S4E6", name: "The Window on the Infinite", expansionId: "S4", description: "", },
  { id: "S5E1", name: "At the Mountains of Madness", expansionId: "S5", description: "", },
  { id: "S5E2", name: "", expansionId: "S5", description: "" },
  { id: "S5E3", name: "Beneath the Waves", expansionId: "S5", description: "" },
  { id: "S5E4", name: "The Nameless City", expansionId: "S5", description: "" },
  { id: "S5E5", name: "The Lost Continent", expansionId: "S5", description: "", },
  { id: "S5E6", name: "Imprisoned with the Pharaohs", expansionId: "S5", description: "", },
  { id: "S6E1", name: "The Doom of Sarnath", expansionId: "S6", description: "" },
  { id: "S6E2", name: "The Enchanted Wood", expansionId: "S6", description: "" },
  { id: "S6E3", name: "A Kingly Meeting", expansionId: "S6", description: "" },
  { id: "S6E4", name: "The Cats of Ulthar", expansionId: "S6", description: "" },
  { id: "S6E5", name: "The Other Gods", expansionId: "S6", description: "" },
  { id: "S6E6", name: "The City", expansionId: "S6", description: "" },
  { id: "LE01", name: "Speak Fhtagn or Die!", expansionId: "Unspeakable Box", description: "", }, 
  { id: "LE02", name: "Bright Lights, Big Monsters", expansionId: "Unspeakable Box", description: "", }, 
  { id: "LE03", name: "Happy Birthday", expansionId: "Unspeakable Box", description: "" }, 
  { id: "LE04", name: "Hypnos", expansionId: "Unknowable Box", description: "" }, 
  { id: "LE05", name: "Dreams in the Witch House", expansionId: "Unknowable Box", description: "", }, 
  { id: "LE06", name: "The Colour Out of Space", expansionId: "Unspeakable Box", description: "", }, 
  { id: "LE07", name: "Horror in the Museum", expansionId: "Unspeakable Box", description: "", }, 
  { id: "LE08", name: "The Towering Inferno", expansionId: "Comic Book Vol. 2", description: "After following a strange creature through a secret passage, we came across a mansion on fire, with weird chanting coming from the basement, strange symbols on the floor, and captives laid out for sacrifice...just another Tuesday night. Let's split up and stop this damn ritual.", }, 
  { id: "LE09", name: "The Cursed Boy", expansionId: "Comic Book Vol. 2", description: "A Mysterious Cult behind the disappearance of a young boy is going to sacrifice him for their ritual. We must find and rescue him before it's too late! The Cult followers are not spilling the ritual's location, but we have ways to make them talk!", }, 
  { id: "LE10", name: "The Rats in the Walls", expansionId: "Unimaginable Box", description: "", }, 
  { id: "LE11", name: "The Case of Charles Dexter Ward", expansionId: "Unimaginable Box", description: "", }, 
  { id: "LE12", name: "Reanimator", expansionId: "Unimaginable Box", description: "", }, 
  { id: "LE13", name: "Through the Gates of the Silver Key", expansionId: "Unimaginable Box", description: "", }, 
  { id: "EPIC01", name: "R'lyeh Rising Epic Episode", expansionId: "R'lyeh Rising", description: "", }, 
  { id: "EPIC02", name: "Godzilla Rising Epic Episode", expansionId: "Godzilla Rising", description: "", }, 
];